language: cpp

os:
- linux
- osx

sudo: required
dist: trusty

osx_image: xcode8.3

compiler:
- gcc
- clang
os:
#- linux
- osx
addons:
  apt:
    sources:
      # Both needed for clang 3.7
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
    - clang-3.7
    - libcrypto++-dev
    - libfuse-dev
install:
- .travisci/install.sh
script:
- .travisci/build_and_test.sh
