language: cpp

os:
- linux
- osx

sudo: required
os: osx
compiler:
# - gcc
- clang

env:
  - BUILD_TARGET=Debug
  - BUILD_TARGET=Release
  - BUILD_TARGET=RelWithDebInfo

matrix:
  allow_failures:
    - os: osx
      env: BUILD_TARGET=Release

install:
- .travisci/install.sh
script:
- .travisci/build_and_test.sh
cache: ccache
